theme: jekyll-theme-forty-jekyll-theme
# site settings
title: Community Blueprint Development
subtitle: Community Blueprint Development Organization
email: drjonestech@gmail.com
description: Template for non-profit education organization 
baseurl: "/Community-Blueprint-Development" # the subpath of your site, e.g. /main
url: # communityblueprintdevelopment.org
author: Cristal Harris, developer
street_address: Restemblance, LLC
city: Atlanta 
state: GA
zip_code: 30096
country: United States of America
phone: 404-585-0311

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/drjonestech
  GitLab:
  Google-Plus:N/A
  Instagram:
  LinkedIn: under construction
  Twitter: under construction
  Facebook:
  Slack:

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md 
